config/routes.rb
Rails.application.routes.draw do
  # get 'articles/new'
  # get 'articles/create'
  # get 'articles/index'
  # get 'articles/show'
  # get 'articles/edit'
  # get 'articles/update'
  # get 'articles/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# create methods - new, create

get 'articles/new', to: 'articles#new'
post 'articles', to: 'articles#create'

# read methods - index, show
get 'articles', to: 'articles#index'
get 'articles/:id', to: 'articles#show', as: 'article'

# update methods - edit, update
get 'articles/:id/edit', to: 'articles#edit', as: 'edit_article'
patch 'articles/:id', to: 'articles#update'

# delete methods - destroy
delete 'articles/:id', to: 'articles#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save

    redirect_to articles_path
  end

  def index
    @articles = Article.all
  end

  def show
  end

  def edit
  end

  def update
    @article.update(article_params)

    redirect_to article_path(params[:id])
  end

  def destroy
    @article.destroy

    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.submit %>
<% end %>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/edit.html.erb
<h1><%= @article.title %></h1>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<% @articles.each do |article| %>
  <h3><%= link_to article.title, article_path(article) %></h3>
  <p><%= article.content %></p>
  <br>
<% end %>

<%= link_to "Add a new article", articles_new_path %>

app/views/articles/new.html.erb
<h1><%= @article.title %></h1>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<%= link_to edit_article_path(@article) do %>
  <i class="far fa-edit"></i>
<% end %>

<%= link_to article_path(@article), method: :delete, data: { confirm: "Are you sure?" } do %>
  <i class="far fa-trash-alt"></i>
<% end %>

<p><%= @article.content %></p>

<%= link_to 'Back to Articles', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css" integrity="sha384-v8BU367qNbs/aIZIxuivaU55N5GPF89WBerHoGA4QTcbUjYiLQtKdrfXnqAcXyTv" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>